name: CI

on: [push, workflow_dispatch]

jobs:
  build-site:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Generate Website
        shell: bash
        run: |
          docker run -v $PWD/static-site:/mnt ldumancas/hugo-build:latest
      
      - name: Save Artifacts
        uses: actions/upload-artifact@v4
        with:
          path: ./static-site/public/
          overwrite: true

      - name: Deploy to S3
        shell: bash
        run: |
          aws s3 sync ./static-site/public s3://lorenzo.dumanc.as
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: 'us-east-2'