name: CI

on: [push, workflow_dispatch]

jobs:
  build-site:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
      
      # - name: Show dir contents
      #   shell: bash
      #   run: |
      #     cd themes/blowfish
      #     ls -la

      - name: Generate Website
        shell: bash
        run: |
          docker run -v $PWD/static-site:/mnt ldumancas/hugo-build:latest
      
      - name: Save Artifacts
        uses: actions/upload-artifact@v4
        with:
          path: ./static-site/public/
          overwrite: true
